#!/bin/sh
VERSION="0.1.1"
version() {
    echo $VERSION && exit 0
}

main() {
    git show-ref --abbrev | grep refs/pull/origin |
    while read -r line;do
        echo ${line#*refs} `git log --author=$author --pretty=format:"%C(yellow)%h %Cred%an %Cblue%ad %Creset%s" -1 --date=short ${line%refs*}`
    done
}

while test $# != 0
do
    case "$1" in
        -v|--version)
            version
            ;;
        --author=*)
            author="${1#--author=}"
            main "$author" && exit 0
            ;;
        --)
            shift
            break
            ;;
    esac
    shift
done
main
